### ISSUE TITLE
  Code variables are a little tricky to understand：  Sp = 10; horizon = 10; T = max(horizon, Sp) 

### ISSUE THREAD

**Issue by zc645080234** [mlpotter/DeepKoopmanLusch#6]
What is the meaning of horizon? When I try to reproduce the discrete example's result of deepkoopman, I set Sp=30 and dataset.shape[1]=51, then X_train_recon.shape[1]=21.  
train_dl = DataLoader(differential_dataset(X_train_recon,T),batch_size=batch_size),
In class differential_dataset() self.T = X.shape[1]-self.horizon is negative, and codes run with errors.
So I want to know the meaning of horizon and differential_dataset(X,horizon), thank you very much.

**Comment by zc645080234** [comment]
![image](https://user-images.githubusercontent.com/53210879/220063801-339c13ca-810e-4a01-9f43-ab8fdf4bb81c.png)

**Comment by mlpotter** [comment]
The horizon is how far into the future you want to forecast. Therefore,  during training, you need to have atleast more time points than the horizon, otherwise you get negative numbers in the data loader which gives an error.
![image](https://user-images.githubusercontent.com/35242331/220161048-5d263f2d-6050-4ee2-9c2c-c94dcd282430.png)

**Comment by zc645080234** [comment]
> The horizon is how far into the future you want to forecast. Therefore, during training, you need to have atleast more time points than the horizon, otherwise you get negative numbers in the data loader which gives an error. ![image](https://user-images.githubusercontent.com/35242331/220161048-5d263f2d-6050-4ee2-9c2c-c94dcd282430.png)

In paper, the first example, the Sp=30, T=max(Sp, horizon)>=30，trajectory=51, X_train_recon = X_train[:,:-T,:]，differential_dataset(X_train_recon,T), 
So then there must be errors, how to fix it?

**Comment by mlpotter** [comment]
Can you give these exact details:

Sp=
horizon=
Time series length=

Time series length must be greater than horizon.

**Comment by zc645080234** [comment]
> 

ok, take the discrete example in Lusch's paper,
Sp=30, horizon=21,Time series length=51
In your codes, T= max(Sp, horizon), then  X_train_recon = X_train[:,:-T,:],differential_dataset(X_train_recon,T), where there must be wrong.
Because Sp *2 is biger than Time series length
Your code is great, but this confuses me

**Comment by zc645080234** [comment]
> Can you give these exact details:
> 
> Sp= horizon= Time series length=
> 
> Time series length must be greater than horizon.

ok, take the discrete example in Lusch's paper,
Sp=30, horizon=21,Time series length=51
In your codes, T= max(Sp, horizon), then X_train_recon = X_train[:,:-T,:],differential_dataset(X_train_recon,T), where there must be wrong.
Because Sp *2 is biger than Time series length
Your code is great, but this confuses me

**Comment by zc645080234** [comment]
> Can you give these exact details:
> 
> Sp= horizon= Time series length=
> 
> Time series length must be greater than horizon.

![image](https://user-images.githubusercontent.com/53210879/221081912-d2684169-218d-496e-a37e-c3ce5ffbd084.png)
![image](https://user-images.githubusercontent.com/53210879/221081963-2c01f8b6-0fbb-4bf1-844e-a8713d4998f5.png)
T equal to or biger than Sp, X_train_recon.shape[1]=21,  differential_dataset(X_train_recon,30), there will be wrong.
And in paper, Sp=30, so it is inevitable.

**Comment by mlpotter** [comment]
Yes I see what you mean. For my purposes since I was trying to do it for some other data I did not code the input shapes for this case you are talking about. I always assumed much larger time series.

You may be able to just change the code so that in line 46,47 in main.py to something like

`
 X_train_recon = X_train[:,:T+1,:]; X_test_recon = X_test[:,:T+1,:]
 X_forecast_train = X_train[:,T+1:,:]; X_forecast_test = X_test[:,T+1:,:]
`

Please let me know if that solves the issue.

**Comment by zc645080234** [comment]
> 

Well, I get it! It is very kind of you to answer my question.

**Comment by mlpotter** [comment]
I think if you just change the indexing like above it should fix the problem you are talking about.
